### ISSUE TITLE
Same OG's list of species and functions in v5 and v6 is inconsistent

### ISSUE THREAD

**Issue by myshu2017-03-14** [eggnogdb/eggnog_docs#11]
Hi，

Recently, I learned the v6 database. But I found that the same OG's list of species and functions in v5 and v6 is inconsistent, eg **COG2100** 

I grep **COG2100**  in the `e6.og2seqs_and_species.tsv` file. And the result just as below:

> 1       LCOG2100        21      23      1797672,1629716,767817,1933779,1531961,1671642,926561,142842,1817893,335541,1734395,868595,1413210,1805125,1712410,957042,926692,1285191,1734399,485916,1121472   1121472.GCA_000376385_01100,1285191.GCA_001592105_00091,1285191.GCA_001592105_00575,1413210.U472_04200,142842.SAMN02745118_00459,1531961.JL50_05755,1629716.VR68_04510,1671642.GCA_001512905_01486,1712410.GCA_000746025_01304,1734395.APF76_06025,1734399.APF77_03380,1797672.A3H36_02465,1805125.AUK23_10985,1817893.AUJ66_01930,1933779.ALI144C_22510,335541.Swol_2405,485916.Dtox_0061,485916.Dtox_3511,767817.Desgi_4624,868595.Desca_0466,926561.GCA_000379025_02121,926692.GCA_000517025_01065,957042.SAMN04515661_104129
2       COG2100 21      23      1797672,1629716,767817,1933779,1531961,1671642,926561,142842,1817893,335541,1734395,868595,1413210,1805125,1712410,957042,926692,1285191,1734399,485916,1121472   1121472.GCA_000376385_01100,1285191.GCA_001592105_00091,1285191.GCA_001592105_00575,1413210.U472_04200,142842.SAMN02745118_00459,1531961.JL50_05755,1629716.VR68_04510,1671642.GCA_001512905_01486,1712410.GCA_000746025_01304,1734395.APF76_06025,1734399.APF77_03380,1797672.A3H36_02465,1805125.AUK23_10985,1817893.AUJ66_01930,1933779.ALI144C_22510,335541.Swol_2405,485916.Dtox_0061,485916.Dtox_3511,767817.Desgi_4624,868595.Desca_0466,926561.GCA_000379025_02121,926692.GCA_000517025_01065,957042.SAMN04515661_104129

And I also grep this to v5 `per_tax_level` directory.
> 1       COG2100 109     109     102129.Lepto7375DRAFT_5841,1033737.CAEV01000024_gene3499,1041930.Mtc_0531,1042877.GQS_02700,1052684.PPM_2827,1056495.Calag_0716,1087481.AGFX01000011_gene4204,1104324.P186_2126,1121381.JNIV01000075_gene2947,1121933.AUHH01000006_gene651,1122921.KB898187_gene4302,1144275.COCOR_04166,1151117.AJLF01000001_gene1200,1163730.FFONT_0311,1183377.Py04_1499,1184251.TCELL_1126,1198449.ACAM_1178,1219375.CM002139_gene3755,1235792.C808_04550,1235802.C823_03758,1242864.D187_003957,1278073.MYSTI_03358,1284352.AOIG01000019_gene3607,1297742.A176_07110,1343739.PAP_07015,1365176.N186_04615,1449063.JMLS01000027_gene18,1536774.H70357_05925,178306.PAE0616,186497.PF1628,195522.BD01_0402,220341.16504726,224325.AF_1810,243232.MJ_0103,246197.MXAN_2889,246969.TAM4_722,267377.MMP0375,272557.APE_1874.1,272844.PAB1998,273063.STK_21740,28072.Nos7524_5268,304371.MCP_0121,316274.Haur_1840,32057.KB217478_gene6920,342949.PNA2_0196,349520.PPE_02624,351160.RCIX269,368408.Tpen_0658,373994.Riv7116_5153,374847.Kcr_1602,378806.STAUR_6299,384616.Pisl_0739,387631.Asulf_01990,391612.CY0110_04251,391623.TERMP_00867,397287.C807_01250,397291.C804_00770,399550.Smar_1327,402880.MmarC5_1300,406327.Mevan_1363,410359.Pcal_0458,411476.BACOVA_00794,411901.BACCAC_02495,415426.Hbut_0274,419665.Maeo_0312,426368.MmarC7_1371,444157.Tneu_1926,444158.MmarC6_0576,453591.Igni_0198,456320.Mvol_1681,456442.Mboo_2248,483215.BACFIN_05022,483219.LILAB_22205,490899.DKAM_0394,523845.AQXV01000023_gene1459,523850.TON_0500,529709.PYCH_03600,565033.GACE_0406,572478.Vdis_2462,572546.Arcpr_1437,573063.Metin_0555,573064.Mefer_0352,579137.Metvu_0341,589924.Ferp_1106,591019.Shell_1122,593117.TGAM_0701,604354.TSIB_1919,633148.Tagg_0699,644281.MFS40622_1015,647113.Metok_1491,666510.ASAC_0347,679926.Mpet_0519,69014.TK1228,693661.Arcve_0705,694429.Pyrfu_0037,698757.Pogu_2591,70601.3258044,709986.Deima_0098,765177.Desmu_0800,768672.Desfe_0363,768679.TTX_2040,864565.HMPREF0379_0524,886882.PPSC2_c3003,90371.CY43_20965,926554.KI912654_gene4515,97139.C824_03717,985053.VMUT_0805,985665.HPL003_19925,999630.TUZN_1443    102129,1033737,1041930,1042877,1052684,1056495,1087481,1104324,1121381,1121933,1122921,1144275,1151117,1163730,1183377,1184251,1198449,1219375,1235792,1235802,1242864,1278073,1284352,1297742,1343739,1365176,1449063,1536774,178306,186497,195522,220341,224325,243232,246197,246969,267377,272557,272844,273063,28072,304371,316274,32057,342949,349520,351160,368408,373994,374847,378806,384616,387631,391612,391623,397287,397291,399550,402880,406327,410359,411476,411901,415426,419665,426368,444157,444158,453591,456320,456442,483215,483219,490899,523845,523850,529709,565033,572478,572546,573063,573064,579137,589924,591019,593117,604354,633148,644281,647113,666510,679926,69014,693661,694429,698757,70601,709986,765177,768672,768679,864565,886882,90371,926554,97139,985053,985665,999630
2       COG2100 39      39      102129.Lepto7375DRAFT_5841,1033737.CAEV01000024_gene3499,1052684.PPM_2827,1087481.AGFX01000011_gene4204,1121381.JNIV01000075_gene2947,1121933.AUHH01000006_gene651,1122921.KB898187_gene4302,1144275.COCOR_04166,1219375.CM002139_gene3755,1235792.C808_04550,1235802.C823_03758,1242864.D187_003957,1278073.MYSTI_03358,1284352.AOIG01000019_gene3607,1297742.A176_07110,1449063.JMLS01000027_gene18,1536774.H70357_05925,220341.16504726,246197.MXAN_2889,28072.Nos7524_5268,316274.Haur_1840,32057.KB217478_gene6920,349520.PPE_02624,373994.Riv7116_5153,378806.STAUR_6299,391612.CY0110_04251,397287.C807_01250,397291.C804_00770,411476.BACOVA_00794,411901.BACCAC_02495,483215.BACFIN_05022,483219.LILAB_22205,709986.Deima_0098,864565.HMPREF0379_0524,886882.PPSC2_c3003,90371.CY43_20965,926554.KI912654_gene4515,97139.C824_03717,985665.HPL003_19925    102129,1033737,1052684,1087481,1121381,1121933,1122921,1144275,1219375,1235792,1235802,1242864,1278073,1284352,1297742,1449063,1536774,220341,246197,28072,316274,32057,349520,373994,378806,391612,397287,397291,411476,411901,483215,483219,709986,864565,886882,90371,926554,97139,985665

The two results are different and the number of v6 is reduced.
What is the reason? Is it an algorithm upgrade? Why are the results so different for v5 and v6?

Best wishes,
Myshu

**Comment by Cantalapiedra** [comment]
Dear @myshu2017-03-14 ,

I don't know the specific details of this, because this is an issue related with eggNOG DB, and not directly with eggNOG-mapper. That being said, note that the Orthologous Groups created in each eggNOG version may be different since new species are included in new releases, and also the orthology is re-computed from (almost) scratch.

Threfore, my guess, although I may be wrong, is that it is expected that the OGs are going to be different from the different eggNOG DB versions.

I hope this makes sense.
Best,
Carlos
